[package]
name = "RustTaskTodo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = "^1"
serde_derive = "^1"
csv = "^1"
uuid = { version = "^1", features = ["v4", "serde"] }
